### ISSUE TITLE
Any advice on how to setup twilio notifications?

### ISSUE THREAD

**Issue by RatebSeirawan** [Gapur/react-native-twilio-chat#1]
I salute you for the comprehensive guide, you have any advice on how to setup twilio push notifications in react-native?

**Comment by Gapur** [comment]
> I salute you for the comprehensive guide, you have any advice on how to setup twilio push notifications in react-native?

Hi Rateb. 
I have implemented Twilio push notifications on web and mobile apps.
What exactly issue did you have with the Twilio push notification?

**Comment by RatebSeirawan** [comment]
> > I salute you for the comprehensive guide, you have any advice on how to setup Twilio push notifications in react-native?
> 
> Hi Rateb.
> I have implemented Twilio push notifications on web and mobile apps.
> What exactly issue did you have with the Twilio push notification?

Hi
Well, I'm in the process of planning the implementation of notifications for chat, I haven't started yet, but if you know a guide or docs that you followed while implementing it that would be very helpful, I couldn't find React Native platform-specific Twilio notifications docs on the Twilio website tho
