### ISSUE TITLE
Login Showing Network Error

### ISSUE THREAD

**Issue by muhamadjawad** [Gapur/react-native-twilio-chat#2]
Hi ,First thanks alot for te guide.
I am facing problem when logging in .What should be the username and where can i define it.When logging in with random username it shows network Error
![network error](https://user-images.githubusercontent.com/50518179/116209937-d3ab1800-a75b-11eb-8f5e-7e997f46add6.jpeg)

The server is running already and the jwt token is returning a positive response.
![image](https://user-images.githubusercontent.com/50518179/116210154-0c4af180-a75c-11eb-96ba-a837f88af994.png)

Now I need your guide and help on i how can I login as user in this app.

**Comment by Gapur** [comment]
Hi Muhammad.

I think you don't have an issue with login because you navigated to the chat list screen. Could you check the chat list request?

Thanks

**Comment by metizror** [comment]
Having Same issue

**Comment by BlagojeV93** [comment]
https://github.com/Gapur/react-native-twilio-chat/issues/3#issuecomment-842006616
