### ISSUE TITLE
Edition For Peer to Peer Chats

### ISSUE THREAD

**Issue by muhamadjawad** [Gapur/react-native-twilio-chat#4]
Hi ,First Thanks for such an amazing work on Twilio. I am successfully ran your code on my PC but now i need some changes. I need to keep the peer to peer chats i.e chats between 2 people only.
Can you tell me how to proceed with is and where do i need changes

**Comment by Gapur** [comment]
Hi! 

This repository is a great example how to work with twilio-chat. You can implement file uploads and push-notification. But it depends upon you! 

Thanks
